name: CI

on:
  push:
  pull_request:

jobs:
  cli:
    name: CLI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cli
    steps:
      - uses: actions/checkout@v4

      - name: Install the Rust toolchain
        run: rustup toolchain install stable --profile minimal --component clippy,rustfmt

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: cli

      - name: Check the formatting
        run: cargo fmt --check

      - name: Lint
        run: cargo clippy --all-targets -- -D warnings

      - name: Test
        run: cargo test
